export const homeObjThree = {
	primary: true,
	lightBg: false,
	imgStart: '',
	lightTopLine: true,
	lightTextDesc: true,
	topLine: 'Contact',
	headline: 'Contact',
	descriptions: 'Email: alex329@mac.com',
	buttonLabel: 'LinkedIn',
	// buttonLabel2: 'Twitter',
	lightText: true,
	img: require('../../Images/contact.svg').default,
	alt: 'Image',
	start: '',
	href1: 'https://www.linkedin.com/in/alexanderanand/',
	// href2: 'https://www.linkedin.com/in/alexanderanand/',
};
