export const homeObjThree = {
	primary: true,
	lightBg: false,
	imgStart: '',
	lightTopLine: true,
	lightTextDesc: true,
	topLine: 'Contact',
	headline: 'Contact',
	descriptions: 'Email: alex329@mac.com Twitter: @alex_codes44',
	buttonLabel: 'LinkedIn',
	lightText: true,
	img: require('../../Images/contact.svg').default,
	alt: 'Image',
	start: '',
};
